name: Public Nuget Publish

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  # push:
  #   branches: [ "releases" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
      
    - name: Restore dependencies
      run: dotnet restore ./RobinMustache.slnx
      
    - name: Build
      run: dotnet build ./RobinMustache.slnx --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ./RobinMustache.slnx --verbosity normal
    
    - name: Pack
      run: dotnet pack ./RobinMustache.slnx --configuration Release -o ./nupkgs
      
    - name: Push
      run: |
        for pkg in ./nupkgs/*.nupkg; do
          echo "Pushing $pkg"
          dotnet nuget push "$pkg" --api-key ${{ secrets.PUBLIC_NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json || true
          sleep 10
        done
